name: Checks

on:
  - pull_request

jobs:
  'prettier:check':
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Check for conflict between eslint and prettier
        run: yarn prettier:check
